import scannedPages from "@/data/sitemap-pages.json";

export type SitemapPage = {
  path: string;
  title: string;
  description: string;
  lastModified: string;
  images: string[];
};

// Link labels that differ from the page title, matching the site navigation.
const labels: Record<string, string> = {
  "/miriams-hope/": "Domestic Violence (Miriam’s Hope)",
};

// Generated by `npm run sitemap:scan`; see scripts/scan-sitemap.mjs.
export const sitemapPages: SitemapPage[] = scannedPages.map((page) => ({
  ...page,
  title: labels[page.path] ?? page.title,
}));

const sections = [
  {
    heading: "Programs",
    paths: [
      "/miriams-hope/",
      "/affordable-housing/",
      "/housing-first/",
      "/homelessness-avoidance/",
      "/care-coach-mobile-unit/",
    ],
  },
  {
    heading: "Get Involved",
    paths: ["/volunteer/", "/live-here-love-here-lake/", "/sponsors/", "/we-need-trailers/"],
  },
  { heading: "Hope In Action", paths: ["/news-media/", "/testimonials/", "/hope-in-action/"] },
  { heading: "About Us", paths: ["/", "/board-staff/", "/contact-us/"] },
  { heading: "Legal", paths: ["/terms-conditions/", "/privacy-policy/", "/sitemap/"] },
];

// Pages the scan finds that no section lists yet still appear under "More Pages".
export function sitemapSections() {
  const listed = new Set(sections.flatMap((section) => section.paths));
  const grouped = sections.map((section) => ({
    heading: section.heading,
    pages: section.paths
      .map((path) => sitemapPages.find((page) => page.path === path))
      .filter((page): page is SitemapPage => Boolean(page)),
  }));
  const unlisted = sitemapPages.filter((page) => !listed.has(page.path));
  return [...grouped, { heading: "More Pages", pages: unlisted }].filter((section) => section.pages.length);
}
